/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.Main;
import java.io.BufferedReader;
import javax.swing.JFileChooser;
import java.io.File;    
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author M.Hakim Amransyah
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     * 
     */
    
    DefaultTableModel data_latih;
    DefaultTableModel data_uji;

    public DefaultTableModel getData_latih() {
        return data_latih;
    }

    public DefaultTableModel getData_uji() {
        return data_uji;
    }
    
    public Home() {
        initComponents();
        this.deskDataLatih.setText("");
        this.deskDataUji.setText("");
        this.doProses.setEnabled(false);
        this.data_latih = (DefaultTableModel) this.Dataset.getModel();
        this.data_uji = new DefaultTableModel();
        this.KNN.setSelected(true);
        this.akurasifknn.setVisible(false);
        this.akurasifknnc.setVisible(false);
        this.log.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dataset = new javax.swing.JTable();
        doProses = new javax.swing.JButton();
        deskDataLatih = new javax.swing.JLabel();
        deskDataUji = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numberOfK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        KNN = new javax.swing.JRadioButton();
        FKNN = new javax.swing.JRadioButton();
        FKNNC = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        akurasiknn = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        akurasifknn = new javax.swing.JLabel();
        akurasifknnc = new javax.swing.JLabel();
        log = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ImportDataLatih = new javax.swing.JMenuItem();
        importDataUji = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        doClear = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("M.Hakim Amransyah");
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Dataset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Dataset.setEnabled(false);
        jScrollPane1.setViewportView(Dataset);

        doProses.setBackground(new java.awt.Color(204, 255, 255));
        doProses.setText("Proses");
        doProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doProsesActionPerformed(evt);
            }
        });

        jLabel1.setText("K Nearest Neighbour");

        numberOfK.setToolTipText("Number of K nearest");
        numberOfK.setName(""); // NOI18N

        jLabel2.setText("Weight");

        KNN.setForeground(new java.awt.Color(0, 0, 204));
        KNN.setText("KNN");
        KNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KNNActionPerformed(evt);
            }
        });

        FKNN.setForeground(new java.awt.Color(204, 0, 0));
        FKNN.setText("FKNN");
        FKNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FKNNActionPerformed(evt);
            }
        });

        FKNNC.setText("FKNNC");
        FKNNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FKNNCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numberOfK)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(KNN)
                            .addComponent(FKNN)
                            .addComponent(FKNNC))
                        .addGap(0, 87, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberOfK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(KNN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FKNN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FKNNC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        akurasiknn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        akurasiknn.setForeground(new java.awt.Color(0, 0, 204));
        akurasiknn.setText("000.0%");

        akurasifknn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        akurasifknn.setForeground(new java.awt.Color(204, 0, 0));
        akurasifknn.setText("000.0%");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(akurasifknn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(akurasifknn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        akurasifknnc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        akurasifknnc.setText("000.0%");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(akurasiknn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(akurasifknnc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(akurasiknn)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(akurasifknnc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        log.setBackground(new java.awt.Color(153, 255, 255));
        log.setText("Log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deskDataUji)
                            .addComponent(deskDataLatih))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doProses, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(deskDataLatih)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deskDataUji)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(doProses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        ImportDataLatih.setText("Import data latih csv");
        ImportDataLatih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportDataLatihActionPerformed(evt);
            }
        });
        jMenu1.add(ImportDataLatih);

        importDataUji.setText("Import data uji csv");
        importDataUji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importDataUjiActionPerformed(evt);
            }
        });
        jMenu1.add(importDataUji);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        doClear.setText("Clear");
        doClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doClearActionPerformed(evt);
            }
        });
        jMenu2.add(doClear);

        jMenuItem2.setText("Clear data uji");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importDataUjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importDataUjiActionPerformed
        this.data_uji.setRowCount(0);
        this.setData(data_uji);
        this.deskDataUji.setText("Jumlah Data Uji : "+this.data_uji.getRowCount());
    }//GEN-LAST:event_importDataUjiActionPerformed

    private void doProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doProsesActionPerformed
        this.initializeKnnType();
        if(!this.numberOfK.getText().toString().equalsIgnoreCase("")){
            Main main = new Main();
            this.setAkurasi(main.doLearn(data_uji, data_latih,Integer.parseInt(this.numberOfK.getText().toString()),this.initializeKnnType()),
                    this.initializeKnnType());         
            this.log.setEnabled(true);
        }
        else{
           JOptionPane.showMessageDialog(null, "Nilai K belum diinputkan");
        }
    }//GEN-LAST:event_doProsesActionPerformed

    private int initializeKnnType(){
        int knntype = 0;
        if(this.KNN.isSelected()){ knntype = 1; }
        else if(this.FKNN.isSelected()){ knntype = 2; }
        else if(this.FKNNC.isSelected()){ knntype = 3; } 
      return knntype;
    }
    private void setData(DefaultTableModel table){
        int i = 0;
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("E:\\POLA"));
        fileChooser.setFileFilter(new FileNameExtensionFilter("csv file", "csv"));
        i = fileChooser.showOpenDialog(this);
        if(i == JFileChooser.APPROVE_OPTION){
            File f = fileChooser.getSelectedFile();
            String d;
            try {
                BufferedReader bf = new BufferedReader(new FileReader(f.getPath()));
                int index=0;
                String[] data = bf.readLine().split(";");
                table.setColumnCount(data.length);
                while((d = bf.readLine())!=null){
                    data = d.split(";");
                    table.insertRow(index, data);
                    index++;
                }       
                this.setProsesButton();
                System.out.println("haha : "+table.getRowCount());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void setProsesButton(){
       if(this.data_latih.getRowCount() != 0 && this.data_uji.getRowCount() != 0){
           this.doProses.setEnabled(true);
       } 
       else{
           this.doProses.setEnabled(false);
       }
    }
    
    private void ImportDataLatihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportDataLatihActionPerformed
        // TODO add your handling code here:
       this.data_latih.setRowCount(0);
       this.setData(this.data_latih);
       this.deskDataLatih.setText("Jumlah Data Latih : "+this.data_latih.getRowCount());
    }//GEN-LAST:event_ImportDataLatihActionPerformed

    private void KNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KNNActionPerformed
        // TODO add your handling code here:
        this.KNN.setSelected(true);
        this.FKNN.setSelected(false);
        this.FKNNC.setSelected(false);
    }//GEN-LAST:event_KNNActionPerformed

    private void FKNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FKNNActionPerformed
        // TODO add your handling code here:
        this.KNN.setSelected(false);
        this.FKNN.setSelected(true);
        this.FKNNC.setSelected(false);
    }//GEN-LAST:event_FKNNActionPerformed

    private void FKNNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FKNNCActionPerformed
        // TODO add your handling code here:
        this.KNN.setSelected(false);
        this.FKNN.setSelected(false);
        this.FKNNC.setSelected(true);
    }//GEN-LAST:event_FKNNCActionPerformed

    private void doClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doClearActionPerformed
        // TODO add your handling code here:
       this.doProses.setEnabled(false);
       this.deskDataLatih.setText("");
       this.deskDataUji.setText("");
       this.data_latih.setRowCount(0);
       this.data_latih.setColumnCount(0);
       this.data_uji.setRowCount(0);
       this.data_uji.setColumnCount(0);
       this.akurasifknn.setVisible(false);
       this.akurasifknnc.setVisible(false);
       this.akurasiknn.setText("000.0%");
    }//GEN-LAST:event_doClearActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        Main main = new Main();
        main.doLog(data_uji, data_latih,Integer.parseInt(this.numberOfK.getText().toString()),this.initializeKnnType());
            
    }//GEN-LAST:event_logActionPerformed
   
    private void setAkurasi(String text,int type){
        if(type == 1){
          this.akurasiknn.setText(text+"%");   
        }
        else if(type == 2){
            
        }else if(type == 3){
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Dataset;
    private javax.swing.JRadioButton FKNN;
    private javax.swing.JRadioButton FKNNC;
    private javax.swing.JMenuItem ImportDataLatih;
    private javax.swing.JRadioButton KNN;
    private javax.swing.JLabel akurasifknn;
    private javax.swing.JLabel akurasifknnc;
    private javax.swing.JLabel akurasiknn;
    private javax.swing.JLabel deskDataLatih;
    private javax.swing.JLabel deskDataUji;
    private javax.swing.JMenuItem doClear;
    private javax.swing.JButton doProses;
    private javax.swing.JMenuItem importDataUji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton log;
    private javax.swing.JTextField numberOfK;
    // End of variables declaration//GEN-END:variables
}
